# Generated by Django 4.2.9 on 2024-03-29 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('neg_price', models.IntegerField(default=0)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.CharField(max_length=50)),
                ('status', models.CharField(default='hold', max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('ownwer_email', models.CharField(max_length=50)),
                ('p_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('det_loc', models.CharField(max_length=50)),
                ('property_name', models.CharField(max_length=50)),
                ('guest_num', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('types', models.CharField(max_length=50)),
                ('view', models.CharField(max_length=50)),
                ('bed', models.CharField(max_length=50)),
                ('common_space', models.CharField(max_length=50)),
                ('tv', models.BooleanField()),
                ('smoking', models.BooleanField()),
                ('air_condition', models.BooleanField()),
                ('bathroom', models.BooleanField()),
                ('water_heater', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('breakfast', models.BooleanField()),
                ('verified', models.BooleanField(default=False)),
                ('p_image1', models.ImageField(null=True, upload_to='images/')),
                ('p_image2', models.ImageField(null=True, upload_to='images/')),
                ('p_image3', models.ImageField(null=True, upload_to='images/')),
                ('p_image4', models.ImageField(null=True, upload_to='images/')),
                ('document', models.BooleanField(default=False)),
                ('doc1', models.FileField(upload_to='documents/')),
                ('doc2', models.FileField(upload_to='documents/')),
                ('doc3', models.FileField(upload_to='documents/')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=20)),
                ('role', models.CharField(default='customer', max_length=20)),
                ('owned_property', models.IntegerField(default=0)),
            ],
        ),
    ]
