# Generated by Django 4.2.9 on 2024-03-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='c_complain',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
