# Generated by Django 4.2.9 on 2024-03-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_uploadedfile_propertydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
