# Generated by Django 4.2.9 on 2024-04-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='voucher',
            field=models.IntegerField(default=0),
        ),
    ]
