# Generated by Django 4.2.9 on 2024-04-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_propertydetails_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
