# Generated by Django 4.2.9 on 2024-03-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_email_propertydetails_ownwer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='ownwer_email',
            field=models.CharField(max_length=50),
        ),
    ]
