# Generated by Django 4.2.9 on 2024-04-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_propertydetails_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='property_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
