# Generated by Django 4.2.9 on 2024-03-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_propertydetails_ownwer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='ownwer_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='p_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
