# Generated by Django 4.2.9 on 2024-04-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_booking_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='book_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
