# Generated by Django 4.2.9 on 2024-03-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_propertydetails_ownwer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='p_image',
        ),
        migrations.AddField(
            model_name='signup',
            name='p_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
