# Generated by Django 4.2.9 on 2024-03-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_propertydetails_p_image_signup_p_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='p_image',
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='p_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
