# Generated by Django 4.2.9 on 2024-03-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_signup_p_image_propertydetails_p_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='air_condition',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='bed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='breakfast',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='common_space',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='det_loc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='parking',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='types',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='wifi',
            field=models.BooleanField(null=True),
        ),
    ]
