# Generated by Django 4.2.9 on 2024-03-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_propertydetails_air_condition_propertydetails_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='view',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
