# Generated by Django 4.2.9 on 2024-03-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_propertydetails_verified_propertydetails_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='role',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
